### ISSUE TITLE
新开TROJAN机场

### ISSUE THREAD

**Issue by wwnice-max** [hwanz/SSR-V2ray-Trojan-vpn#1]
新开机场(TROJAN), 机场内测，开放注册，无需邀请码, 无付费订阅计划，简单邮箱注册

内测：测试 VPS 节点稳定性，vps 节点选型，陆续会接入大量节点（高性能节点）

机场地址: https://www.xflash.cc

**Comment by yemao221** [comment]
2024年最稳定梯子VPN，科学上网2年亲测稳定，56元畅享一年！   
地址：https://www.xxxlsop.com/#/register?code=sf9UTRC0    


🔥全年2300GB高速流量  
针对亚洲优化的IEPL中转方案  
palm world 团队的热门产品  

🌍 奈飞、迪士尼等流媒体解锁 畅享国际热门流媒体  
💡 ChatGPT解锁 - 无障碍访问ChatGPT  
🌐 全球10个国家接入 - 全球多点接入  
🛡️ 99.99% SLA 保证 - 高可靠性服务等级协议  
⚡ 1000Mbps 带宽保证 - 超高速带宽。  
💻 20台客户端同时登录 - 轻量用户的选择。    
[![QQ20240824-134644](https://github.com/user-attachments/assets/6edfdb33-c6bc-492a-8f17-c8d4348a27a2)](https://www.xxxlsop.com/#/register?code=sf9UTRC0)
